#
# Bootstrap program is omake.boot
#
default:
	@echo "If you have already built omake, you should use it instead of make."
	@echo "If you need to bootstrap, use "
	@echo " - 'nmake -f Makefile.nt bootstrap',"
	@echo "       to build the bootstrapping (feature-limited) OMake binary './omake-boot'."
	@echo " - 'nmake -f Makefile.nt all',"
	@echo "       to bootstrap and then build everything."
	@echo " - 'nmake -f Makefile.nt install',"
	@echo "       to bootstrap, build, and install everything."
	@exit 1

NMAKE = $(MAKE) /nologo -f Makefile.nt

bootstrap: boot\Makefile.nt boot\Makefile.dep
	cd boot
	$(NMAKE) Makefile.dep
	$(NMAKE) omake.exe
	copy omake.exe ..\omake-boot.exe
	cd ..

all: bootstrap
	echo # Empty config > .config
	set OMAKEFLAGS=
	set OMAKEPATH=lib
	.\omake-boot --dotomake .omake --force-dotomake -j2 -S --progress main
	src\main\omake --dotomake .omake --force-dotomake -j2 -S --progress all

install: all
	set OMAKEFLAGS=
	set OMAKEPATH=lib
	.\omake-boot --dotomake .omake --force-dotomake -j2 -S --progress install

boot\Makefile.nt: src\Makefile.nt
	-mkdir boot
	copy src\Makefile.nt boot\Makefile.nt

boot\Makefile.dep:
	echo # Dependencies > $@
